[[headers]]
  # Cache assets with -H- hash (defined in main.ts)
  for = "/*-H-*"
    [headers.values]
    cache-control = '''
      max-age=31536000,
      immutable'''
  # Cache fonts as it's quite unlikely that they will change
  for = "/*.woff2"
    [headers.values]
    cache-control = '''
      max-age=31536000,
      immutable'''
  for="/assets/versions.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
