name: Update versions.json
description: Updates the versions.json file with latest info from a release

runs:
  using: composite
  steps:
    - name: Update versions.json
      run: echo "Im such a test action!"
