name: Release old demo App to Netlify

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: use local action
        uses: ./.github/actions/test-action
